name: Release & Publish Package to NPM

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get CI Bot Token
        uses: tibdex/github-app-token@v2
        id: ci_bot_token
        with:
          app_id: ${{ secrets.CI_BOT_APP_ID }}
          private_key: ${{ secrets.CI_BOT_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.ci_bot_token.outputs.token }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install the dependencies
        run: npm ci
      - name: Initialize Git User
        run: |
          git config --global user.email "github-actions[bot]@genlayer.com"
          git config --global user.name "github-actions[bot]"
      - name: Initialize the NPM configuration
        run: npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ steps.ci_bot_token.outputs.token }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
